# Generated by Django 3.0.3 on 2020-02-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20)),
                ('bpub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hName', models.CharField(max_length=10)),
                ('hGender', models.BooleanField()),
                ('hContent', models.CharField(max_length=20)),
                ('hText', models.CharField(default=0, max_length=20)),
                ('hBook', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='yywSite.BookInfo')),
            ],
        ),
    ]
